import asyncio
import json
import time
from openai import AsyncOpenAI
from .base.completion import Completion
from tqdm import tqdm
from .base import (
    DEFAULT_MODEL_CONFIGURATION,
    Conversation,
    ModelConfiguration,
    Tool,
    ToolCall,
    get_first_element,
    parse_logprobs,
)


async def generate_completion_for_conversation(
    conversation: Conversation,
    model_configuration: ModelConfiguration | None = None,
) -> Completion:
    """Generate a tool call completion from a conversation.

    This function sends the conversation to the OpenAI API with the provided tools,
    and returns the tool calls that the model generates.

    Args:
        conversation: The conversation to generate a tool call completion for.
        tools: A Tool object or a list of Tool objects that define the available tools for the model.
        model_configuration: Optional configuration for the model. If None, uses the default configuration.

    Returns:
        A ToolCallCompletion object containing the tool calls generated by the model.
    """
    if model_configuration is None:
        model_configuration = DEFAULT_MODEL_CONFIGURATION

    tools = model_configuration.tool
    if isinstance(tools, Tool):
        tools = [tools]

    client = AsyncOpenAI(
        api_key=model_configuration.api_key,
        base_url=model_configuration.base_url,
    )

    openai_tools = [tool.openai_tool for tool in tools]

    start_time = time.time()
    completion = await client.chat.completions.create(
        model=model_configuration.model,
        messages=conversation.openai_messages,
        temperature=model_configuration.temperature,
        logprobs=model_configuration.log_probs,
        top_logprobs=model_configuration.top_log_probs,
        max_tokens=model_configuration.max_tokens,
        presence_penalty=model_configuration.presence_penalty,
        frequency_penalty=model_configuration.frequency_penalty,
        top_p=model_configuration.top_p,
        seed=model_configuration.seed,
        tools=openai_tools,
    )
    end_time = time.time()

    first_choice = get_first_element(completion.choices)
    if first_choice is None:
        raise ValueError("No choices returned from the completion.")

    message_content = first_choice.message.content or first_choice.message.parsed

    if message_content is None:
        raise ValueError("No message content returned from the completion.")

    full_token_log_probs = parse_logprobs(first_choice)

    openai_tool_calls = first_choice.message.tool_calls or []

    tool_calls = [
        ToolCall(
            id=tool_call.id,
            name=tool_call.function.name,
            arguments=json.loads(tool_call.function.arguments),
        )
        for tool_call in openai_tool_calls
    ]

    return Completion(
        content=message_content,
        model=model_configuration.model,
        conversation=conversation,
        start_time=start_time,
        end_time=end_time,
        tool_calls=tool_calls,
        full_token_log_probs=full_token_log_probs,
    )


async def generate_completion(
    user_prompt: str,
    system_prompt: str | None = None,
    model_configuration: ModelConfiguration | None = None,
) -> Completion:
    """
    Generate a tool call completion for a user prompt.

    This function creates a conversation from the provided prompts and generates
    tool calls based on the available tools.

    Args:
        user_prompt: The user prompt to generate a tool call for.
        tools: A Tool object or a list of Tool objects that define the available tools for the model.
        system_prompt: Optional system prompt to use for the conversation.
        model_configuration: Optional configuration for the model. If None, uses the default configuration.

    Returns:
        A ToolCallCompletion object containing the generated tool calls.
    """
    if model_configuration is None:
        model_configuration = DEFAULT_MODEL_CONFIGURATION

    conversation = Conversation.from_prompts(
        user_prompt, system_prompt=system_prompt)

    return await generate_completion_for_conversation(
        conversation,
        model_configuration=model_configuration,
    )


async def generate_completions_for_conversations(
    conversations: list[Conversation],
    model_configuration: ModelConfiguration | None = None,
    n_parallel: int = 5,
    show_progress: bool = True,
) -> list[Completion]:
    completions = []

    progress_bar = None

    if show_progress:
        progress_bar = tqdm(total=len(conversations))

    for i in range(0, len(conversations), n_parallel):
        conversations_batch = conversations[i: i + n_parallel]

        tasks = [
            asyncio.create_task(
                generate_completion_for_conversation(
                    conversation,
                    model_configuration,
                )
            )
            for conversation in conversations_batch
        ]

        completions_batch = await asyncio.gather(*tasks)
        completions.extend(completions_batch)

        if show_progress and progress_bar is not None:
            progress_bar.update(len(completions_batch))

    if show_progress and progress_bar is not None:
        progress_bar.close()

    return completions


async def generate_completions(
    user_prompts: list[str],
    system_prompt: str | None = None,
    tools: Tool | list[Tool] = [],
    n_parallel: int = 5,
    model_configuration: ModelConfiguration | None = None,
    show_progress: bool = True,
) -> list[Completion]:
    conversations = [
        Conversation.from_prompts(user_prompt, system_prompt=system_prompt)
        for user_prompt in user_prompts
    ]

    return await generate_completions_for_conversations(
        conversations,
        n_parallel=n_parallel,
        model_configuration=model_configuration,
        show_progress=show_progress,
    )
